" First set basic settings.
source ~/.vim/vimrc-parts/basic.vim

" Add some features to Vim
source ~/.vim/vimrc-parts/plugin.vim
source ~/.vim/vimrc-parts/html-text-object-linewise.vim
source ~/.vim/vimrc-parts/open-on-last-position.vim
source ~/.vim/vimrc-parts/search-match-blink.vim

" Set mappings and abbreviations
source ~/.vim/vimrc-parts/abbreviation.vim
source ~/.vim/vimrc-parts/mapping.vim
